### ISSUE TITLE
Proposal: Hand ownership of this project over to the graphql foundation or a similar community-driven group

### ISSUE THREAD

**Issue by wheresrhys** [graphql/graphql-playground#1100]
This is a _really_ great project but
- the list of issues and the frequency of commits and releases indicates it is clearly undermaintained
- Prisma have declared that they are pivoting into a slightly different field, no longer specilising in GraphQL, so to expect them to devote the time this project needs to maintain it is probably not realistic.

**Comment by timsuchanek** [comment]
Thanks @wheresrhys for raising this, we're aware that this project needs some love again, because of that we're in discussion with the community to hand the project over.

I can't disclose anything yet, but we'll soon give you an update on the future of this project!
