### ISSUE TITLE
Add schema settings to Settings interface

### ISSUE THREAD

**Issue by etylermoss** [graphql/graphql-playground#1211]
#### This issue pertains to the following package(s):

- [ ] GraphQL Playground - Electron App
- [x] GraphQL Playground HTML
- [ ] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?
N/A

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
graphql-playground-html@1.6.19

#### What is the expected behavior?
ISettings interface should contain settings pertaining to Schema polling, so that it can be set automatically, not by each client. These are the polling properties:
```
'schema.polling.enable': string
'schema.polling.endpointFilter': string
'schema.polling.interval': number
```
#### What is the actual behavior?
ISettings does not contain these properties, so the settings object has to be cast `as any` in order to not cause a Typescript error (`ts(2322)`):
```ts
settings: {
	...
	'schema.polling.enable': false, // error, does not exist in type 'RecursivePartial<ISettings>
} // `as any` for temporary fix
```

**Comment by oliversalzburg** [comment]
Why not just include all the options in the schema? And why not at least merge #1212 to fix some of this?
