### ISSUE TITLE
Playground is not updating

### ISSUE THREAD

**Issue by ragokan** [graphql/graphql-playground#1309]
#### This issue pertains to the following package(s):

- [ ] GraphQL Playground - Electron App
- [ ] GraphQL Playground HTML
- [X] GraphQL Playground
- [x] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?
Windows 10

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
1.7.33 if I am sure

#### What is the expected behavior?
Update the documents when I reload.

#### What is the actual behavior?
The schema is not updating when I press reload button. The only solution to update the schema is reloading the page totally.

_Please provide a gif or image of the issue for a quicker response/fix._
![image](https://user-images.githubusercontent.com/63511519/104856644-f0e27600-5924-11eb-8a49-6914fe119eba.png)

**Comment by Fitmavincent** [comment]
Not updating +1, same here. The schema not reloading at all, especially on the remote server.

**Comment by ragokan** [comment]
> Not updating +1, same here. The schema not reloading at all, especially on the remote server.

Yeah, I don't know how can I fix. I used helmet, cors, other browser, other ports, clear browser data, nothing works.

**Comment by acao** [comment]
we are going to put out a release to disable automatic schema polling again sometime when I have a chance in the next month. try disabling it and see if this addresses this issue

**Comment by ragokan** [comment]
> we are going to put out a release to disable automatic schema polling again sometime when I have a chance in the next month. try disabling it and see if this addresses this issue

Well, I think that the problem is not related only with graphql-playground, it probably have something to do with apollo-server-express because when I use graphql-playground-middleware-express, there are no problem.

**Comment by acao** [comment]
are you using their fork `@apollo-graphql/graphql-playground`? or `graphql-playground-react` directly. the desktop app hasn't been updated in about two years

**Comment by FBurner** [comment]
having the same problem now

**Comment by Fitmavincent** [comment]
Have you guys try this: ```php artisan lighthouse:clear-cache```
