### ISSUE TITLE
Couldn't load bcp-config.json

### ISSUE THREAD

**Issue by woeterman94** [graphql/graphql-playground#1313]
#### This issue pertains to the following package(s):

- [ ] GraphQL Playground - Electron App
- [x ] GraphQL Playground HTML
- [ ] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?
Azure app service (linux container) 

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
![image](https://user-images.githubusercontent.com/5755057/106439373-e624f680-6477-11eb-94f4-0ef027fd326d.png)
V11.0.9

#### What is the expected behavior?
The playground should load an show all schema's

#### What is the actual behavior?
Playground load, but shows no schema's.
![image](https://user-images.githubusercontent.com/5755057/106439096-97775c80-6477-11eb-9ac0-138566263bef.png)
Network tab shows an error (see below)

#### What steps may we take to reproduce the behavior?
Navigating to the /graphql url

_Please provide a gif or image of the issue for a quicker response/fix._
![image](https://user-images.githubusercontent.com/5755057/106438997-7f074200-6477-11eb-9565-a70baf21681e.png)

**Comment by danieldybsland** [comment]
I have the exact same issue (500 error), upon deploying this as a app service on Azure: https://starwars20210206142735.azurewebsites.net/graphql/

Is there something that should have been deployed with the solution, that's missing?

**Comment by michaelstaib** [comment]
I only stumbled by accident over this issue. Had you filed it on the correct repo you would've gotten a response :D
