### ISSUE TITLE
subscription websocket connection failed in graphql but works locally and with frontend application.

### ISSUE THREAD

**Issue by saurav-bhagat** [graphql/graphql-playground#1329]
#### This issue pertains to the following package(s):

- [ ] GraphQL Playground - Electron App
- [ ] GraphQL Playground HTML
- [ ] GraphQL Playground
- [x] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?
Windows 10

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
"graphql-playground-middleware-express": "1.7.18",

#### What is the expected behavior?
Subscription Websocket connection should be made with the server using the playground.

#### What is the actual behavior?
WebSocket is closed before the connection is established (From the network tab)
Could not connect to websocket endpoint wss://<host>/subscription. Please check if the endpoint url is correct

#### What steps may we take to reproduce the behavior?
I'm using Apollo server express ("2.18.2") with subscription endpoint as "/subscription". This works fine in the localhost playground. 
I deployed the application in my EKS cluster and now tried to make subscription connection to server with my react application and it worked as expected but when I open playground, I'm unable to connect to subscription. 
All normal queries and mutations are working fine from the playground. Just the websocket connection.

In Apollo client I have passed, reconnect: true as option, is there any similar option for playground?
What could be the issue?

**Comment by saurav-bhagat** [comment]
This was really strange, my browser cache, I tried using a different browser and it worked. 
Apology for the inconvenience.

**Comment by stvreumi** [comment]
Thank you for reporting this issue. I recently learn how to use subscription, but I can't use the playground on my brave browser to connect to the server I just created. Even the [apollo example in the document](https://www.apollographql.com/docs/apollo-server/data/subscriptions/#basic-runnable-example) can't work.
Then I saw this issue and change my browser to firefox, it works...
