### ISSUE TITLE
Static folder missing in 1.7.27 release of graphql-playground-react

### ISSUE THREAD

**Issue by janhommes** [graphql/graphql-playground#1344]
#### This issue pertains to the following package(s):

- [X] GraphQL Playground React

#### What OS and OS version are you experiencing the issue(s) on?
Linux

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
1.7.27

#### What is the expected behavior?
https://unpkg.com/browse/graphql-playground-react@1.7.27/build/ should contain a /static folder (like the versions before).

#### What is the actual behavior?
https://unpkg.com/browse/graphql-playground-react@1.7.27/build/ does not contain a /static folder

#### What steps may we take to reproduce the behavior?
👀https://unpkg.com/browse/graphql-playground-react@1.7.27/build/

**Comment by jdrydn** [comment]
Any chance someone can look at this? I'd like to host a private Playground internally & set authentication data using #992, however without a `/static` folder in `1.7.27` I can't use the global headers feature!

**Comment by jdrydn** [comment]
As a stop-gap in the meantime, here's some instructions to build the static folder by-hand (assuming Git & Docker is installed & configured):

```sh
$ git clone git@github.com:graphql/graphql-playground
$ cd graphql-playground
$ docker run --rm -it -w /workspace -v $PWD:/workspace node:12 /bin/bash
```

And within the container:
```
# yarn
# cd packages/graphql-playground-react
# yarn build
```

Now `./packages/graphql-playground-react/build` will exist & contain a `/static` folder. Upload that to a static hosting provider of your choice (e.g. S3) and reference in [`./index.html`](https://github.com/graphql/graphql-playground/blob/main/packages/graphql-playground-html/minimal.html#L8-L10) appropriately.

**Comment by janhommes** [comment]
It seems like somehow (I am very confused by the versioning of this project :/) a new release was made and this version contains a static folder again:
https://unpkg.com/browse/graphql-playground-react@1.7.28/build/

So I am closing this issue.
