### ISSUE TITLE
How to add subscription url on latest version

### ISSUE THREAD

**Issue by nouh** [graphql/graphql-playground#365]
#### This issue pertains to the following package(s):

- [x] GraphQL Playground - Electron App
- [ ] GraphQL Playground HTML
- [ ] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What steps may we take to reproduce the behavior?

_Please provide a gif or image of the issue for a quicker response/fix._

**Comment by timsuchanek** [comment]
Right now you have to use https://github.com/graphcool/graphql-config and open the project with the `graphql playground` in that folder. We're working on making that easier, so you can just provide the subscriptions url in the ui.
