### ISSUE TITLE
Reload schema does not reload enum that is already used in a type

### ISSUE THREAD

**Issue by divyenduz** [graphql/graphql-playground#537]
#### This issue pertains to the following package(s):

- [x] GraphQL Playground - Electron App
- [x] GraphQL Playground HTML
- [ ] GraphQL Playground - Quick question, If electron app and HTML are covered, not sure what this one is. 
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?
macOS High Sierra - 10.13.2

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
1.4.2

#### What is the expected behavior?
I changed and deployed an enum (already used in another type) from this

```
enum Tags {
  NEWS
  SUCCESS_STORY
  HISTORY
  PHILOSOPHY
}
```

to this 

```
enum Tags {
  HOME
  PRODUCT
  CAREER
  PHILOSOPHY
}
```

As the product requirements changed but Playground wouldn't fetch the new enum values and won't let me fire any queries as it statically finds that my enum is wrong. 

Playground should refresh the enum when "reload schema" is performed. 

#### What is the actual behavior?
Playground does not refresh an enum when "reload schema" is performed. 

#### What steps may we take to reproduce the behavior?
Create an enum and a type, fire a query against the type including the enum. 
Change the enum, try to use the new enum values in your query. 

Playground wouldn't have refreshed the values, I also tried web playground, re-installing playground.

Apart from this I tried to go to mysql via docker and change types to what I need (to move forward) but then while loading this enum, prisma is happy, but playground turns it to null as it lands on an unexpected enum type. 

Please let me know if I can go around this in any way? Or if I can provide more information to help us resolve this. 

Thanks for putting in all the hard work in GraphQL ecosystem 👍

**Comment by divyenduz** [comment]
Also, this is a super hunch though but could this issue be related to this one?
https://github.com/graphcool/graphql-import/issues/59

**Comment by timsuchanek** [comment]
Thanks for reporting @divyenduz !
It is possible that the `graphql-import` is related, but from my view unlikely.

**Comment by divyenduz** [comment]
Yes, I also feel it is unlikely as the projects are not dependent on each other. I will pick this issue up sometime in February if it is not taken by then. 

Thanks.
